package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCriminal_record <br>
 * @version generated on Thu Nov 12 17:28:24 CET 2020 by Piotr
 */
public class DefaultCriminal_record extends WrappedIndividualImpl implements Criminal_record {

    public DefaultCriminal_record(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
