package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultGender <br>
 * @version generated on Sat Oct 24 10:43:14 CEST 2020 by Michał Barczyk
 */
public class DefaultGender extends WrappedIndividualImpl implements Gender {

    public DefaultGender(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
