package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultFemale <br>
 * @version generated on Fri Sep 04 18:08:06 CEST 2020 by Michał Barczyk
 */
public class DefaultFemale extends WrappedIndividualImpl implements Female {

    public DefaultFemale(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
