package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultRoad_attributes <br>
 * @version generated on Sun Nov 15 23:20:33 CET 2020 by Michał Barczyk
 */
public class DefaultRoad_attributes extends WrappedIndividualImpl implements Road_attributes {

    public DefaultRoad_attributes(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#bridge
     */
     
    public Collection<? extends Boolean> getBridge() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BRIDGE, Boolean.class);
    }

    public boolean hasBridge() {
		return !getBridge().isEmpty();
    }

    public void addBridge(Boolean newBridge) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BRIDGE, newBridge);
    }

    public void removeBridge(Boolean oldBridge) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BRIDGE, oldBridge);
    }


    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#controlled_access
     */
     
    public Collection<? extends Boolean> getControlled_access() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONTROLLED_ACCESS, Boolean.class);
    }

    public boolean hasControlled_access() {
		return !getControlled_access().isEmpty();
    }

    public void addControlled_access(Boolean newControlled_access) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONTROLLED_ACCESS, newControlled_access);
    }

    public void removeControlled_access(Boolean oldControlled_access) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_CONTROLLED_ACCESS, oldControlled_access);
    }


    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#ferry
     */
     
    public Collection<? extends Boolean> getFerry() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FERRY, Boolean.class);
    }

    public boolean hasFerry() {
		return !getFerry().isEmpty();
    }

    public void addFerry(Boolean newFerry) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FERRY, newFerry);
    }

    public void removeFerry(Boolean oldFerry) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_FERRY, oldFerry);
    }


    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#motorway
     */
     
    public Collection<? extends Boolean> getMotorway() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MOTORWAY, Boolean.class);
    }

    public boolean hasMotorway() {
		return !getMotorway().isEmpty();
    }

    public void addMotorway(Boolean newMotorway) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MOTORWAY, newMotorway);
    }

    public void removeMotorway(Boolean oldMotorway) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_MOTORWAY, oldMotorway);
    }


    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#service_area
     */
     
    public Collection<? extends Boolean> getService_area() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SERVICE_AREA, Boolean.class);
    }

    public boolean hasService_area() {
		return !getService_area().isEmpty();
    }

    public void addService_area(Boolean newService_area) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SERVICE_AREA, newService_area);
    }

    public void removeService_area(Boolean oldService_area) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_SERVICE_AREA, oldService_area);
    }


    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#toll
     */
     
    public Collection<? extends Boolean> getToll() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOLL, Boolean.class);
    }

    public boolean hasToll() {
		return !getToll().isEmpty();
    }

    public void addToll(Boolean newToll) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOLL, newToll);
    }

    public void removeToll(Boolean oldToll) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TOLL, oldToll);
    }


    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#tunnel
     */
     
    public Collection<? extends Boolean> getTunnel() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TUNNEL, Boolean.class);
    }

    public boolean hasTunnel() {
		return !getTunnel().isEmpty();
    }

    public void addTunnel(Boolean newTunnel) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TUNNEL, newTunnel);
    }

    public void removeTunnel(Boolean oldTunnel) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_TUNNEL, oldTunnel);
    }


    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#urban
     */
     
    public Collection<? extends Boolean> getUrban() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_URBAN, Boolean.class);
    }

    public boolean hasUrban() {
		return !getUrban().isEmpty();
    }

    public void addUrban(Boolean newUrban) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_URBAN, newUrban);
    }

    public void removeUrban(Boolean oldUrban) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_URBAN, oldUrban);
    }


}
