package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAdult <br>
 * @version generated on Wed Dec 02 14:25:00 CET 2020 by Mateusz
 */
public class DefaultAdult extends WrappedIndividualImpl implements Adult {

    public DefaultAdult(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
