package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultCondition <br>
 * @version generated on Fri Oct 02 20:54:13 CEST 2020 by Michał Barczyk
 */
public class DefaultCondition extends WrappedIndividualImpl implements Condition {

    public DefaultCondition(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
