package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultHuman_profession <br>
 * @version generated on Wed Dec 02 14:25:01 CET 2020 by Mateusz
 */
public class DefaultHuman_profession extends WrappedIndividualImpl implements Human_profession {

    public DefaultHuman_profession(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
