package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultLane <br>
 * @version generated on Sat Jul 18 17:20:52 CEST 2020 by Michał Barczyk
 */
public class DefaultLane extends WrappedIndividualImpl implements Lane {

    public DefaultLane(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#lane_width
     */
     
    public Collection<? extends Integer> getLane_width() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LANE_WIDTH, Integer.class);
    }

    public boolean hasLane_width() {
		return !getLane_width().isEmpty();
    }

    public void addLane_width(Integer newLane_width) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LANE_WIDTH, newLane_width);
    }

    public void removeLane_width(Integer oldLane_width) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_LANE_WIDTH, oldLane_width);
    }


}
