package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultRoad_attributes <br>
 * @version generated on Sat Oct 17 17:24:31 CEST 2020 by Michał Barczyk
 */
public class DefaultRoad_attributes extends WrappedIndividualImpl implements Road_attributes {

    public DefaultRoad_attributes(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
