package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPreposition <br>
 * @version generated on Sun Nov 15 23:20:32 CET 2020 by Michał Barczyk
 */
public class DefaultPreposition extends WrappedIndividualImpl implements Preposition {

    public DefaultPreposition(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
