package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultOut_of_vehicle <br>
 * @version generated on Sat Nov 21 14:40:16 CET 2020 by Michał Barczyk
 */
public class DefaultOut_of_vehicle extends WrappedIndividualImpl implements Out_of_vehicle {

    public DefaultOut_of_vehicle(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
