package project;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Lane <br>
 * @version generated on Sat Jul 18 17:20:52 CEST 2020 by Michał Barczyk
 */

public interface Lane extends WrappedIndividual {

    /* ***************************************************
     * Property http://webprotege.stanford.edu/project/BDGSqwMbfBgw7pUJ8IOnJ1#lane_width
     */
     
    /**
     * Gets all property values for the lane_width property.<p>
     * 
     * @returns a collection of values for the lane_width property.
     */
    Collection<? extends Integer> getLane_width();

    /**
     * Checks if the class has a lane_width property value.<p>
     * 
     * @return true if there is a lane_width property value.
     */
    boolean hasLane_width();

    /**
     * Adds a lane_width property value.<p>
     * 
     * @param newLane_width the lane_width property value to be added
     */
    void addLane_width(Integer newLane_width);

    /**
     * Removes a lane_width property value.<p>
     * 
     * @param oldLane_width the lane_width property value to be removed.
     */
    void removeLane_width(Integer oldLane_width);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
